name: Update Challenges JSON
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run script file
        run: |
          chmod +x ./github/workflows/scripts/script.sh
          ./github/workflows/scripts/script.sh
        shell: bash

      - name: Committing and Pushing Changes
        run: |
          git commit -am "Update challenges.json"
          git push origin master
